Filtering Proposals by Status and Scheme
DXgovernance/dxvote pull request #240
Opened 2021-10-11 22:39 UTC by luchux

Filter and sort proposals initially with the following requirements: 

Proposals in Queued or QuietEndingPeriod status with more than 10% of positive votes. (Ordered from time to finish, from lower to higher)
Proposals Boosted. (Ordered from time to finish, from lower to higher)
Proposals Pre Boosted.
Proposals in Queued or QuietEndingPeriod status with lower than 10% of positive votes. (Ordered from time to finish, from lower to higher)
Proposals in Executed status. (Ordered in time passed since finish, from lower to higher)

If Status filtering applied, filter by that status. 
if Scheme filtering applied, also filter by schema. 
if Title search, also filter by title. 
[in a chained filtering fashion]

<img width="1440" alt="Screen Shot 2021-10-12 at 6 06 40 PM" src="https://user-images.githubusercontent.com/1475656/137049529-ce681f39-a6e6-469b-8394-a521991a8058.png">
<img width="1439" alt="Screen Shot 2021-10-12 at 6 06 32 PM" src="https://user-images.githubusercontent.com/1475656/137049540-827e92a1-44c9-47cd-b711-9bd36db7de00.png">
<img width="1440" alt="Screen Shot 2021-10-12 at 6 06 22 PM" src="https://user-images.githubusercontent.com/1475656/137049544-6df25e15-4aee-4937-9107-9e5d8d2a8975.png">
<img width="1416" alt="Screen Shot 2021-10-12 at 6 06 09 PM" src="https://user-images.githubusercontent.com/1475656/137049551-7dd5a3d4-b012-4152-b066-d5ec8f049b6c.png">

2021-10-13 01:05 UTC, luchux commented
@rossneilson @AugustoL 
So some comments on this solution: 
- I am applying the filterInitialCriteria function for filtering and sorting and described by AugustoL in this feature. 
- I am generating the State Filter <option>'s from the enum VotingMachineProposalState now. Should we provide more than those? 
- Schema filter, and search by title is applied after the result of State filter:  If 'Any Status', those schemes and title mach from the initial criteria filtering. If Status is selected, scheme and title filter from those results. 
- Can we move the filterInitialCriteria function to a helper? I am using the repAt to calculate the % of votes, so we need access to the daoStore from the helper if we do so.  (or can we calculate that % posiitves,  from the data in the proposal object ? without the repAt? ) 
- I removed any type of filter at Component rendering Level, (it was a filter when iterating over the proposals and rendering each row). Now the whole array gets rendered, and the that array is the one that is filtered in each criteria (no more conditional rendering). 
- I see another PR that touched a lot of the title search filtering https://github.com/DXgovernance/dxvote/pull/244/files, I can manage to merge this filtering title way with my changes.

2021-10-13 17:48 UTC, AugustoL requested changes

2021-10-13 17:48 UTC, AugustoL commented on src/pages/Proposals.tsx
> +    let earliestAbove10 = proposals.filter(
Can we take this value form a constant in utils? Somehing like `QueuedPriorityThresold`, so we can change it later easily in case we want to.

2021-10-13 17:48 UTC, AugustoL commented on src/pages/Proposals.tsx
> +      // is it necessary to all this datoSTore.getRepAt?
Yes! Because this is the total supply of the REP token when that proposal was created. and based on that and the REP used in votes we calculate the percentage of votes.

2021-10-13 21:29 UTC, luchux commented on src/pages/Proposals.tsx
> +    let earliestAbove10 = proposals.filter(
done! great call

2021-10-13 21:29 UTC, luchux commented on src/pages/Proposals.tsx
> +      // is it necessary to all this datoSTore.getRepAt?
OKOK!

2021-10-14 07:59 UTC, AugustoL reviewed
I added a few comments, then looks we good.

2021-10-14 07:59 UTC, AugustoL commented on src/utils/proposals.ts
> +//is it added in Cache?
Sorry I just saw this, yes it is, in Proposal.boostedPhaseTime. Do we need it though? Because we are calculating already the time that a proposal will finish based on their status and boostedPhaseTime before ordering, right?

2021-10-14 07:59 UTC, AugustoL commented on src/utils/proposals.ts
> +export const orderByNewestTimeSinceFinished = (a: any, b: any) =>
hmmm, not sure if I understand, but yes (? The finishTime received by the decodeProposalStatus gives us the time that the proposal is predicted to finish. And I guess that yes, we want to order the proposals based on their finish time sometimes.

Also this function does the same as the function above. And the variable is called `finishTime` so maybe lets just use only the function declared above `orderByNewestTimeToFinish` ?

2021-10-14 09:46 UTC, luchux commented on src/utils/proposals.ts
> +export const orderByNewestTimeSinceFinished = (a: any, b: any) =>
@AugustoL yeah my bad here. Created 2 thinking for time passed since finished we had another param) 
"Proposals in Executed status. (Ordered in time passed since finish, from lower to higher)" ... the passed since finish is already calcuted in  finishTime of decodeProposalStatus for the executed ;) .

let 2 in case it was another field to look for. removing in a bit

2021-10-14 09:47 UTC, luchux commented on src/utils/proposals.ts
> +export const orderByNewestTimeSinceFinished = (a: any, b: any) =>
good catch perrico ;)

2021-10-14 09:55 UTC, luchux commented on src/utils/proposals.ts
> +//is it added in Cache?
oh for typescript params. Cause in some params we are accessing proposal.boostTime so we can't type that as Proposal, but may be a type for it that i didn't see. ;) will check it

2021-10-14 09:55 UTC, luchux commented on src/utils/proposals.ts
> +//is it added in Cache?
if not will make the type extending Proposal and adding the missing fields

2021-10-14 16:10 UTC, AugustoL approved these changes

2021-10-15 18:24 UTC, merged