Feature/guilds status modal
DXgovernance/dxvote pull request #440
Opened 2021-11-30 06:19 UTC by luchux

This PR Does: 
- Adds useClickOutside hook to keep an event on mouse down out of an element and call a callback. 
- use useClickOutside in the menus scheme and status filters, and member menu, to close them when clicking out. 

- Adds modal to Join DXDAo and join button on sidebar. 
- Adds menu on sidebar for when the user is member already. 
- Refactor styles of MenuContent so we can tell if should show a menu in fullscreen in mobile. 
 
 video: 
 https://watch.screencastify.com/v/ERtPmDAiTMYkxJiniHOC

2021-11-30 09:02 UTC, hhamud requested changes, later dismissed
The Build fails 
![image](https://user-images.githubusercontent.com/53880692/144017044-e8ec7df3-e92f-41b4-8868-d9d9b36520c5.png)

2021-11-30 20:04 UTC, hhamud submitted a review, later dismissed
It works great! but there are a few issues.

2021-11-30 20:04 UTC, hhamud commented on src/configs/localhost/config.json
> +    "ipfsHash": "QmVz2vSovUfKuvtugoo8AtSJnV6cXiqixVsA8TLgv4Fxzv"
was this supposed to be committed and pushed here?

2021-11-30 20:04 UTC, hhamud commented on src/configs/proposalTitles.json
> -  "0x08382f2197b647b338a15bcb33287dc3edc278f8c089a12952b87ee3fbadb42a": "Update swapr.eth resolver to point to beta 8.1 release of Swapr",
Same thing? was this supposed to be changed here?

2021-11-30 20:04 UTC, hhamud commented on src/hooks/Guilds/useClickOutside.ts
> +export const useClickOutside = (ref, callback) => {
you should add the comment here again on the purpose of this hook. I don't immediately know what `useClickOutside` is supposed to do. Or you can make the name clearer

2021-12-01 23:52 UTC, luchux commented
@hhamud we are ok with the configs, we can re generate them anytime. I put things in a lot of commits stupidly, and its hard to revert and remove to the actual state of main. 
So Ross, gave the ok to go with them as their to avoid much handling.

2021-12-02 00:09 UTC, hhamud approved these changes
LGTM!

2021-12-02 12:20 UTC, rossneilson commented on src/components/Guilds/Sidebar/GuestActions.tsx
> +        header={<ModalHeader>Join DxDao</ModalHeader>}
"DXdao" is the correct formatting here

2021-12-02 12:20 UTC, rossneilson commented on src/components/Guilds/Sidebar/GuestActions.tsx
> +export const GuestActions = ({ onJoin }) => {
Could we make the padding more like the figma design in this component?
Currently a large space below the header and very cramped at the bottom

2021-12-02 22:26 UTC, merged

2021-12-02 22:27 UTC, luchux commented
@rossneilson merged this and will update your changes and new changes that were added today at the figma in another issue ticket.