Feat/signed messages
DXgovernance/dxvote pull request #547
Opened 2022-01-04 14:30 UTC by AugustoL

2022-01-11 09:41 UTC, rossneilson submitted a review, later dismissed

2022-01-11 11:17 UTC, hhamud requested changes

2022-01-11 11:17 UTC, hhamud commented on src/components/Proposal/Votes/index.tsx
> +            signedVote[6]
it would be helpful if you added a quick comment on what these represent exactly

2022-01-11 11:17 UTC, hhamud commented on src/components/Proposal/Votes/index.tsx
> +        signedVoteMessage.split(':').length > 6
it would improve the readability to encapsulate these into a single function

2022-01-11 11:17 UTC, hhamud commented on src/components/Proposal/Votes/index.tsx
> +    }
break this nested ifs up

2022-01-11 11:17 UTC, hhamud commented on src/components/Proposal/Votes/index.tsx
> +                      signedVote => signedVote.vote.toString() === '1'
I've seen this repeated multiple times, best to create a function

2022-01-11 11:17 UTC, hhamud commented on src/services/DaoService.ts
> +    console.log('Hashed vote:', hashedVote);
is this still needed?

2022-01-11 11:17 UTC, hhamud commented on src/services/MessageLoggerService.ts
> +      console.log(`Rinkeby tx signature: ${v}${r}${s}`);
more console.logs

2022-01-11 11:17 UTC, hhamud commented on src/services/MessageLoggerService.ts
> +    console.log('Unsigned Rinkeby tx:', tx);
same thing

2022-01-11 11:17 UTC, hhamud commented on src/services/MessageLoggerService.ts
> +    let filter = messageLogger.filters.Message(topic);
switch this to a const

2022-01-11 11:17 UTC, hhamud commented on src/services/MessageLoggerService.ts
> +    console.log(filter);
same thing

2022-01-11 11:17 UTC, hhamud commented on src/stores/Provider.ts
> +    console.log(dataToSign);
same thing

2022-01-11 11:17 UTC, hhamud commented on src/stores/Provider.ts
> +    console.log(dataToSign);
same thing

2022-01-11 11:17 UTC, hhamud commented on src/utils/cache.ts
> +    // console.error('Error decoding descriptionHash', descriptionHash);
best to remove this if its no longer needed

2022-01-11 11:18 UTC, hhamud commented
I've assumed during this review that ross has tested the changes out and that he's happy with them. I've only focused on a few things within the codebase

2022-01-11 22:57 UTC, AugustoL commented
@hhamud I did most of the changes you commented, I couldnt remove the if in the submitSigned votes because the functions executed depend on different sync conditions like if the vote if valid and where to share it,etc.

2022-01-12 10:21 UTC, rossneilson commented
> I've assumed during this review that ross has tested the changes out and that he's happy with them. I've only focused on a few things within the codebase

Correct, although there may be some bugs I could not find any breaking ones and we want to get this into QA and tested ASAP

2022-01-12 10:22 UTC, rossneilson submitted a review, later dismissed

2022-01-12 11:47 UTC, merged