Get guild instance data - Create a single contract instance on context.
DXgovernance/dxvote pull request #557
Opened 2022-01-08 17:12 UTC by MiltonTulli

### Summary: 
- Create guildConfig context
- Create providerService context
- Pull guild contract info and store it inside context. 

### Issue(s): 
https://github.com/DXgovernance/dxvote/issues/539

2022-01-10 10:23 UTC, mprasanjith requested changes
I'd suggest to move the ConfigContext and Provider to `src/contexts/Guilds` and `useGuildConfig` hook to `src/hooks/Guilds` for consistency.

2022-01-10 20:32 UTC, MiltonTulli commented
> I'd suggest to move the ConfigContext and Provider to `src/contexts/Guilds` and `useGuildConfig` hook to `src/hooks/Guilds` for consistency.

Done. I put `useGuildConfig` under `hooks/Guilds`

2022-01-11 10:09 UTC, rossneilson approved these changes, later dismissed

2022-01-11 11:31 UTC, luchux submitted a review, later dismissed
awesome work!

2022-01-12 09:52 UTC, mprasanjith submitted a review, later dismissed
Looks good! I think this PR also contains changes that we should update to use SWR. Pinging @luchux for visiblity.

2022-01-12 09:52 UTC, mprasanjith commented on src/contexts/Guilds/config.tsx
> +  }, [web3Context.chainId, address]); // eslint-disable-line react-hooks/exhaustive-deps
Is it possible to fix this without disabling the eslint rule?

2022-01-12 10:19 UTC, rossneilson submitted a review, later dismissed
Looks great, lets follow it up with SWR after also

2022-01-12 16:20 UTC, luchux commented
@mprasanjith @MiltonTulli 
We are changing a bunch of the way we read the data in Guilds page and each Proposal page. 
Do you guys think we should wait a bit with this PR, to see when we need the context? useEtherSWR removes the need of keeping a context (if we use directly the data as is stored in the EtherSWR cache,  and also if we add a middleware to EtherSWR we can manipulate and store the data in a post-processed after fetch way - like adding metadata -, then we wont need a context). But still would be interesting to analyze if we need stuff like that or not. 

I would not discard this changes, as if we remove useEtherSWR this is the way to go, but will put on hold (and not even try to fix the conflicts). 

What are your thoughts?

2022-01-12 18:24 UTC, hhamud commented
> @mprasanjith @MiltonTulli We are changing a bunch of the way we read the data in Guilds page and each Proposal page. Do you guys think we should wait a bit with this PR, to see when we need the context? useEtherSWR removes the need of keeping a context (if we use directly the data as is stored in the EtherSWR cache, and also if we add a middleware to EtherSWR we can manipulate and store the data in a post-processed after fetch way - like adding metadata -, then we wont need a context). But still would be interesting to analyze if we need stuff like that or not.
> 
> I would not discard this changes, as if we remove useEtherSWR this is the way to go, but will put on hold (and not even try to fix the conflicts).
> 
> What are your thoughts?


I say we place this into draft mode for now and work on extending EtherSWR

2022-01-12 22:20 UTC, MiltonTulli commented
> > @mprasanjith @MiltonTulli We are changing a bunch of the way we read the data in Guilds page and each Proposal page. Do you guys think we should wait a bit with this PR, to see when we need the context? useEtherSWR removes the need of keeping a context (if we use directly the data as is stored in the EtherSWR cache, and also if we add a middleware to EtherSWR we can manipulate and store the data in a post-processed after fetch way - like adding metadata -, then we wont need a context). But still would be interesting to analyze if we need stuff like that or not.
> > I would not discard this changes, as if we remove useEtherSWR this is the way to go, but will put on hold (and not even try to fix the conflicts).
> > What are your thoughts?
> 
> I say we place this into draft mode for now and work on extending EtherSWR

Sure. I prefer closing this PR since we are going to implement SWR lib and that won't require any config context or contract methods call as I have done here. That was something that wasn't clear when started working on this. Will close this pr and work on a new implementation. Thanks all!

2022-01-12 22:20 UTC, closed without merging