Feature/proposal page data wireup
DXgovernance/dxvote pull request #558
Opened 2022-01-10 10:11 UTC by mprasanjith

This change introduces real data from the guilds smart contracts into the proposal page. Changes to show the actual sidebar content and call data will be included in a follow-up PR.

![image](https://user-images.githubusercontent.com/25136207/148748798-6c400e2d-c187-421e-9f5f-410d6247ca16.png)

Remarks:
- I didn't access the ProposalsContext to get the proposal data as we probably will refactor this soon with the `swr` implementation. 
- The WalletButton component has been split into two. The new `AddressButton` component is a generic component that supports showing any Ethereum address and avatar.
- We should define a schema for the proposal metadata stored in IPFS soon. For now I added a placeholder `ProposalMetadata` interface with just a description field.
- We need to have a generic error component to show in case something failed while loading data.

Closes #542.

2022-01-10 15:16 UTC, hhamud requested changes
Overall it works great, just a few stylistic changes.

2022-01-10 15:16 UTC, hhamud commented on src/components/Guilds/AddressButton/index.tsx
> +  let imageUrlToUse = useMemo(() => {
use const here instead

2022-01-10 15:16 UTC, hhamud commented on src/hooks/Guilds/proposals/useProposal.ts
> +export const useProposal = (
same thing here.

2022-01-10 15:16 UTC, hhamud commented on src/hooks/Guilds/ipfs/useIPFSNode.ts
> +export default function useIPFSNode() {
convert to es6 style.

2022-01-10 15:16 UTC, hhamud commented on src/hooks/Guilds/ipfs/useIPFSNode.ts
> +  }
same thing here

2022-01-10 15:19 UTC, hhamud commented
![image](https://user-images.githubusercontent.com/53880692/148790436-b62a1ca9-308b-4fb4-b4ad-a6d37d391fd9.png)
an issue here with the address icon

2022-01-11 09:53 UTC, rossneilson commented
Think this is supposed to be below the title but above the description
<img width="701" alt="Screenshot 2022-01-11 at 10 52 57" src="https://user-images.githubusercontent.com/39137239/148920542-d96d6d94-62c3-4650-b39b-add9a9b98c71.png">

2022-01-11 18:53 UTC, luchux approved these changes, later dismissed

2022-01-11 21:37 UTC, hhamud approved these changes
LGTM!

2022-01-12 10:18 UTC, rossneilson approved these changes

2022-01-12 13:16 UTC, merged